# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2021-2025 California Institute of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details

name: GitHub Release

on:
  push:
    tags:
      - v*

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: "GitHub Release"

        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
